macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

test_task:
  name: Test

  env:
    PATH: $HOME/miniconda3/bin/:$PATH
    PY_VER: "3.10.7"

  pyenv_script:
    - which python3
    - python3 --version
    - brew update
    - brew install pyenv
    - pyenv install 3.10.7
    - pyenv global 3.10.7
    - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
    - echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
    - echo 'eval "$(pyenv init -)"' >> ~/.zshrc
    - source ~/.zshrc
    - which python3
    - which python3.10
    - python3 --version
    - curl -sSL https://install.python-poetry.org | python -
