macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

test_task:
  name: Test

  env:
    PATH: $HOME/miniconda3/bin/:$PATH
    PY_VER: "3.10.7"

  submodules_script:
    - git submodule init
    - git submodule update

  python_script:
    - brew update
    - brew install pyenv
    - pyenv install $PV_VER
    - pyenv global $PV_VER
    - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
    - echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
    - echo 'eval "$(pyenv init -)"' >> ~/.zshrc

  poetry_script:
    - source ~/.zshrc
    - curl -sSL https://install.python-poetry.org | python3 -
    - echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc

  ffmpeg_script:
    - brew install ffmpeg

  dependencies_script:
    - source ~/.zshrc
    - poetry config experimental.new-installer false && poetry install

  test_script:
    - source ~/.zshrc
    - poetry run make test
