macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

setup_dependencies_template: &SETUP_DEPENDENCIES_TEMPLATE
  env:
    PYTHON_VERSION: "3.10.7"
    PATH: ${HOME}/.local/bin:${PATH}

  submodules_script:
    - git submodule init
    - git submodule update

  python_script:
    - brew update
    - brew install pyenv
    - pyenv install $PYTHON_VERSION
    - pyenv global $PYTHON_VERSION
    - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
    - echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
    - echo 'eval "$(pyenv init -)"' >> ~/.zshrc

  poetry_script:
    - source ~/.zshrc
    - curl -sSL https://install.python-poetry.org | python3 -
    - poetry config experimental.new-installer false
    - poetry config virtualenvs.create true
    - poetry config virtualenvs.in-project true

  ffmpeg_script:
    - brew install ffmpeg

  whisper_cpp_cache:
    folder: $HOME/Library/Caches/Buzz

  whisper_cache:
    folder: $HOME/.cache/whisper

  huggingface_cache:
    folder: $HOME/.cache/huggingface

  dependencies_script:
    - poetry install

#test_task:
#  name: Test
#
#  <<: *SETUP_DEPENDENCIES_TEMPLATE
#
#  test_script:
#    - source .venv/bin/activate
#    - poetry run make test
#
#  coverage_artifacts:
#    path: coverage.xml

build_task:
  name: Build

  <<: *SETUP_DEPENDENCIES_TEMPLATE

  build_script:
    - source .venv/bin/activate
    - poetry run make dist/Buzz.app zip_mac

  zip_artifacts:
    name: buzz
    path: dist/Buzz-*.zip
