macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-base:latest

setup_dependencies_template: &SETUP_DEPENDENCIES_TEMPLATE
  env:
    PYTHON_VERSION: "3.10.7"
    PATH: ${HOME}/.local/bin:${PATH}
    BUZZ_CODESIGN_IDENTITY: ENCRYPTED[4c7e3ce59dc42025d6aa87a9adf09aa529eac7319f522e1b52c5c190234cf7da5b3622ab4117070e49891cbba7afdf40]
    BUZZ_KEYCHAIN_NOTARY_PROFILE: ENCRYPTED[8a06421168e11f921a0bd981ea01db0a57d729364f24a5d290a30b708237e5f574718dbc26d856a6b8c2570524b50408]
    BUILD_CERTIFICATE_BASE64: ENCRYPTED[b2dfad9875af42440e3dbb24472b737bd936c7ccaf2fba3681f6b92c1e9aa8c9be44d9a06da80eda5c27471364e386de]
    KEYCHAIN_PASSWORD: ENCRYPTED[e01d4f6eee93b3cf190843686b0e065b8f2a9641730b35e63b9528dda8aa813554fafc86664c9777e425e8f4f7621c58]
    P12_PASSWORD: ENCRYPTED[0bfe79e5a9348ea5245181d568d04b1dcd7ff34717cced115d8d80d85179f0957b2f49944ab9a19a8999126e077b15e1]
    APPLE_ID: ENCRYPTED[c0cafef2bad1756b404d617993f3eddb85654b4342b7a865d2ca07a545063d611bcd9ea2b795edd914fb41cc7aa03cef]
    APPLE_APP_PASSWORD: ENCRYPTED[8ac00ae3216a09541aa03304e72957c274908257a291adf3ee0ac2d38abe987a35bea52159ad00862485da9c68700468]
    APPLE_TEAM_ID: ENCRYPTED[4c7e3ce59dc42025d6aa87a9adf09aa529eac7319f522e1b52c5c190234cf7da5b3622ab4117070e49891cbba7afdf40]

  submodules_script:
    - git submodule init
    - git submodule update

  python_script:
    - brew update
    - brew install pyenv
    - pyenv install $PYTHON_VERSION
    - pyenv global $PYTHON_VERSION
    - echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
    - echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
    - echo 'eval "$(pyenv init -)"' >> ~/.zshrc

  poetry_script:
    - source ~/.zshrc
    - curl -sSL https://install.python-poetry.org | python3 -
    - poetry config experimental.new-installer false
    - poetry config virtualenvs.create true
    - poetry config virtualenvs.in-project true

  #  ffmpeg_script:
  #    - brew install ffmpeg

  #  dependencies_cache:
  #    folder: .venv
  #    fingerprint_script: cat poetry.lock
  #    populate_script:
  #      - poetry install

  whisper_cpp_cache:
    folder: $HOME/Library/Caches/Buzz

  whisper_cache:
    folder: $HOME/.cache/whisper

  huggingface_cache:
    folder: $HOME/.cache/huggingface

#test_task:
#  name: Test
#
#  <<: *SETUP_DEPENDENCIES_TEMPLATE
#
#  test_script:
#    - source ~/.zshrc
#    - poetry run make test
#
#  coverage_artifacts:
#    path: coverage.xml

build_task:
  name: Build

  <<: *SETUP_DEPENDENCIES_TEMPLATE

  build_script:
    - poetry install
    - source .venv/bin/activate
    - brew install create-dmg
    - |
      # create variables
      CERTIFICATE_PATH=build_certificate.p12
      KEYCHAIN_PATH=app-signing.keychain-db
      
      # import certificate and provisioning profile from secrets
      echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
      
      # create temporary keychain
      security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
      security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      
      security default-keychain -s $KEYCHAIN_PATH
      
      # import certificate to keychain
      security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
      security list-keychain -d user -s $KEYCHAIN_PATH
      
      # store notarytool credentials
      xcrun notarytool store-credentials --apple-id "$APPLE_ID" --password "$APPLE_APP_PASSWORD" --team-id "$APPLE_TEAM_ID" notarytool --validate
    - poetry run make bundle_mac
