---
name: CI
'on': push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            CMD_BUILD: >
              brew install create-dmg
              poetry run make bundle_mac version=rc
            PATH: |
              dist/buzz*.dmg
              dist/buzz*.zip
          - os: windows-latest
            CMD_BUILD: >
              poetry run make buzz
            PATH: |
              dist/Buzz.exe
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'

      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-2

      - run: poetry install
      - run: ${{ matrix.CMD_BUILD }}
      - uses: actions/upload-artifact@v3
        with:
          name: Buzz
          path: |
            ${{ matrix.PATH }}
